### ISSUE TITLE
Allow putting to an image with environment variable updates

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/concourse-kpack-resource#4]
Often pipelines contain information that will get updated with and needs to be applied as an environment variable. 

Some examples of this are:
- A pipeline rebuilding [tomcat](https://github.com/paketo-buildpacks/apache-tomcat) configuration and updating the env var to point at the newest version:  BP_TOMCAT_EXT_CONF_URI 
- Providing a version to the build to the build as environment variable that comes from the semantic version resource. (kpack itself would use this as we currently hard-code the value.)

```
- put: some-image
  params:
     environment_variables:
          BP_GO_TARGET: "./cmd/controller"
     environment_variables_file:
          CUSTOM_VERSION: "version-resource/version" 
```    
Then: the build-service image is updated with the provided env variables.

* Is there a better name then environment_variables_file?
